# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setStyleSheet("\n"
"    /* 전체 앱 스타일 */\n"
"    QMainWindow {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    \n"
"    /* 사이드바 스타일 */\n"
"    QFrame#frame_sidebar {\n"
"        background-color: #2c3e50;\n"
"        border-radius: 10px;\n"
"        margin: 5px;\n"
"    }\n"
"    \n"
"    /* 로그인 버튼 스타일 */\n"
"    QPushButton#pushButton_login {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        padding: 8px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#pushButton_login:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    \n"
"    /* 메뉴 리스트 스타일 */\n"
"    QListWidget#listWidget_menu {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: white;\n"
"        font-size: 14px;\n"
"    }\n"
"    QListWidget#listWidget_menu::item {\n"
"        padding: 10px;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QListWidget#listWidget_menu::item:selected {\n"
"        background-color: #34495e;\n"
"    }\n"
"    QListWidget#listWidget_menu::item:hover {\n"
"        background-color: #34495e;\n"
"    }\n"
"    \n"
"    /* 메인 컨텐츠 영역 스타일 */\n"
"    QStackedWidget#stackedWidget_main {\n"
"        background-color: white;\n"
"        border-radius: 10px;\n"
"        margin: 5px;\n"
"    }\n"
"    \n"
"    /* 테이블 스타일 */\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        border: 1px solid #e0e0e0;\n"
"        border-radius: 5px;\n"
"        gridline-color: #f0f0f0;\n"
"    }\n"
"    QTableWidget::item {\n"
"        padding: 5px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #f8f9fa;\n"
"        padding: 5px;\n"
"        border: none;\n"
"        border-right: 1px solid #e0e0e0;\n"
"        border-bottom: 1px solid #e0e0e0;\n"
"        font-weight: bold;\n"
"    }\n"
"    \n"
"    /* 콤보박스 스타일 */\n"
"    QComboBox {\n"
"        border: 1px solid #bdc3c7;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        background-color: white;\n"
"    }\n"
"    QComboBox:hover {\n"
"        border-color: #3498db;\n"
"    }\n"
"    \n"
"    /* 버튼 스타일 */\n"
"    QPushButton {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        padding: 8px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    \n"
"    /* 로그 영역 스타일 */\n"
"    QTextEdit#textEdit_log {\n"
"        background-color: #2c3e50;\n"
"        color: #ecf0f1;\n"
"        border-radius: 5px;\n"
"        padding: 10px;\n"
"        font-family: Consolas, Monaco, monospace;\n"
"    }\n"
"    \n"
"    /* 스핀박스 스타일 */\n"
"    QSpinBox {\n"
"        border: 1px solid #bdc3c7;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        background-color: white;\n"
"    }\n"
"    QSpinBox:hover {\n"
"        border-color: #3498db;\n"
"    }\n"
"    \n"
"    /* 라벨 스타일 */\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-weight: bold;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.frame_sidebar = QtWidgets.QFrame(self.centralwidget)
        self.frame_sidebar.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_sidebar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sidebar.setObjectName("frame_sidebar")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.frame_sidebar)
        self.verticalLayout_sidebar.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_sidebar.setSpacing(15)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_sidebar)
        self.pushButton_login.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_sidebar.addWidget(self.pushButton_login)
        self.listWidget_menu = QtWidgets.QListWidget(self.frame_sidebar)
        self.listWidget_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_menu.setObjectName("listWidget_menu")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_menu.addItem(item)
        self.verticalLayout_sidebar.addWidget(self.listWidget_menu)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_sidebar.addItem(spacerItem)
        self.horizontalLayout_main.addWidget(self.frame_sidebar)
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_account = QtWidgets.QWidget()
        self.page_account.setObjectName("page_account")
        self.verticalLayout_account = QtWidgets.QVBoxLayout(self.page_account)
        self.verticalLayout_account.setSpacing(15)
        self.verticalLayout_account.setObjectName("verticalLayout_account")
        self.frame_account_info = QtWidgets.QFrame(self.page_account)
        self.frame_account_info.setObjectName("frame_account_info")
        self.horizontalLayout_account = QtWidgets.QHBoxLayout(self.frame_account_info)
        self.horizontalLayout_account.setObjectName("horizontalLayout_account")
        self.label_account = QtWidgets.QLabel(self.frame_account_info)
        self.label_account.setObjectName("label_account")
        self.horizontalLayout_account.addWidget(self.label_account)
        self.comboBox_account = QtWidgets.QComboBox(self.frame_account_info)
        self.comboBox_account.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_account.setObjectName("comboBox_account")
        self.horizontalLayout_account.addWidget(self.comboBox_account)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_account.addItem(spacerItem1)
        self.verticalLayout_account.addWidget(self.frame_account_info)
        self.pushButton_refresh_balance = QtWidgets.QPushButton(self.page_account)
        self.pushButton_refresh_balance.setMinimumHeight(35)
        self.pushButton_refresh_balance.setObjectName("pushButton_refresh_balance")
        self.pushButton_refresh_balance.setText("잔고 새로고침")
        self.verticalLayout_account.addWidget(self.pushButton_refresh_balance)
        self.tableWidget_balance = QtWidgets.QTableWidget(self.page_account)
        self.tableWidget_balance.setObjectName("tableWidget_balance")
        self.tableWidget_balance.setColumnCount(0)
        self.tableWidget_balance.setRowCount(0)
        self.verticalLayout_account.addWidget(self.tableWidget_balance)
        self.pushButton_manual_sell = QtWidgets.QPushButton(self.page_account)
        self.pushButton_manual_sell.setMinimumHeight(35)
        self.pushButton_manual_sell.setObjectName("pushButton_manual_sell")
        self.pushButton_manual_sell.setText("수동 매도")
        self.verticalLayout_account.addWidget(self.pushButton_manual_sell)
        self.tableWidget_orders = QtWidgets.QTableWidget(self.page_account)
        self.tableWidget_orders.setObjectName("tableWidget_orders")
        self.tableWidget_orders.setColumnCount(8)
        self.tableWidget_orders.setHorizontalHeaderLabels([
            '주문번호', '종목코드', '종목명', '주문수량', '주문가격', '주문상태', '주문유형', '시간'])
        self.verticalLayout_account.addWidget(self.tableWidget_orders)
        self.stackedWidget_main.addWidget(self.page_account)
        self.page_condition = QtWidgets.QWidget()
        self.page_condition.setObjectName("page_condition")
        self.verticalLayout_condition = QtWidgets.QVBoxLayout(self.page_condition)
        self.verticalLayout_condition.setSpacing(15)
        self.verticalLayout_condition.setObjectName("verticalLayout_condition")
        self.frame_condition_controls = QtWidgets.QFrame(self.page_condition)
        self.frame_condition_controls.setObjectName("frame_condition_controls")
        self.verticalLayout_condition_controls = QtWidgets.QVBoxLayout(self.frame_condition_controls)
        self.verticalLayout_condition_controls.setSpacing(10)
        self.verticalLayout_condition_controls.setObjectName("verticalLayout_condition_controls")
        self.comboBox_condition = QtWidgets.QComboBox(self.frame_condition_controls)
        self.comboBox_condition.setMinimumHeight(35)
        self.comboBox_condition.setObjectName("comboBox_condition")
        self.verticalLayout_condition_controls.addWidget(self.comboBox_condition)
        self.pushButton_load_conditions = QtWidgets.QPushButton(self.frame_condition_controls)
        self.pushButton_load_conditions.setMinimumHeight(35)
        self.pushButton_load_conditions.setObjectName("pushButton_load_conditions")
        self.verticalLayout_condition_controls.addWidget(self.pushButton_load_conditions)
        self.pushButton_save_condition = QtWidgets.QPushButton(self.frame_condition_controls)
        self.pushButton_save_condition.setMinimumHeight(35)
        self.pushButton_save_condition.setObjectName("pushButton_save_condition")
        self.verticalLayout_condition_controls.addWidget(self.pushButton_save_condition)
        self.pushButton_start_condition = QtWidgets.QPushButton(self.frame_condition_controls)
        self.pushButton_start_condition.setMinimumHeight(35)
        self.pushButton_start_condition.setObjectName("pushButton_start_condition")
        self.verticalLayout_condition_controls.addWidget(self.pushButton_start_condition)
        self.frame_cut_settings = QtWidgets.QFrame(self.frame_condition_controls)
        self.frame_cut_settings.setObjectName("frame_cut_settings")
        self.horizontalLayout_cut = QtWidgets.QHBoxLayout(self.frame_cut_settings)
        self.horizontalLayout_cut.setObjectName("horizontalLayout_cut")
        self.label_loss_cut = QtWidgets.QLabel(self.frame_cut_settings)
        self.label_loss_cut.setObjectName("label_loss_cut")
        self.horizontalLayout_cut.addWidget(self.label_loss_cut)
        self.spinBox_loss_cut = QtWidgets.QSpinBox(self.frame_cut_settings)
        self.spinBox_loss_cut.setMinimumSize(QtCore.QSize(80, 30))
        self.spinBox_loss_cut.setMinimum(1)
        self.spinBox_loss_cut.setMaximum(100)
        self.spinBox_loss_cut.setProperty("value", 5)
        self.spinBox_loss_cut.setObjectName("spinBox_loss_cut")
        self.horizontalLayout_cut.addWidget(self.spinBox_loss_cut)
        self.label_gain_cut = QtWidgets.QLabel(self.frame_cut_settings)
        self.label_gain_cut.setObjectName("label_gain_cut")
        self.horizontalLayout_cut.addWidget(self.label_gain_cut)
        self.spinBox_gain_cut = QtWidgets.QSpinBox(self.frame_cut_settings)
        self.spinBox_gain_cut.setMinimumSize(QtCore.QSize(80, 30))
        self.spinBox_gain_cut.setMinimum(1)
        self.spinBox_gain_cut.setMaximum(100)
        self.spinBox_gain_cut.setProperty("value", 5)
        self.spinBox_gain_cut.setObjectName("spinBox_gain_cut")
        self.horizontalLayout_cut.addWidget(self.spinBox_gain_cut)
        self.verticalLayout_condition_controls.addWidget(self.frame_cut_settings)
        self.verticalLayout_condition.addWidget(self.frame_condition_controls)
        self.tableWidget_condition_stocks = QtWidgets.QTableWidget(self.page_condition)
        self.tableWidget_condition_stocks.setObjectName("tableWidget_condition_stocks")
        self.tableWidget_condition_stocks.setColumnCount(0)
        self.tableWidget_condition_stocks.setRowCount(0)
        self.verticalLayout_condition.addWidget(self.tableWidget_condition_stocks)
        self.stackedWidget_main.addWidget(self.page_condition)
        self.page_log = QtWidgets.QWidget()
        self.page_log.setObjectName("page_log")
        self.verticalLayout_log = QtWidgets.QVBoxLayout(self.page_log)
        self.verticalLayout_log.setObjectName("verticalLayout_log")
        self.textEdit_log = QtWidgets.QTextEdit(self.page_log)
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        self.verticalLayout_log.addWidget(self.textEdit_log)
        self.stackedWidget_main.addWidget(self.page_log)
        self.horizontalLayout_main.addWidget(self.stackedWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kiwoom Trader"))
        self.pushButton_login.setText(_translate("MainWindow", "로그인"))
        __sortingEnabled = self.listWidget_menu.isSortingEnabled()
        self.listWidget_menu.setSortingEnabled(False)
        item = self.listWidget_menu.item(0)
        item.setText(_translate("MainWindow", "계좌/잔고"))
        item = self.listWidget_menu.item(1)
        item.setText(_translate("MainWindow", "조건식 매매"))
        item = self.listWidget_menu.item(2)
        item.setText(_translate("MainWindow", "로그"))
        self.listWidget_menu.setSortingEnabled(__sortingEnabled)
        self.label_account.setText(_translate("MainWindow", "계좌번호"))
        self.pushButton_load_conditions.setText(_translate("MainWindow", "조건식 불러오기"))
        self.pushButton_save_condition.setText(_translate("MainWindow", "조건식 저장"))
        self.pushButton_start_condition.setText(_translate("MainWindow", "조건식 감시 시작"))
        self.frame_cut_settings.setStyleSheet(_translate("MainWindow", "\n"
"               QFrame#frame_cut_settings {\n"
"                 background-color: #f8f9fa;\n"
"                 border-radius: 5px;\n"
"                 padding: 10px;\n"
"               }\n"
"              "))
        self.label_loss_cut.setText(_translate("MainWindow", "손절 기준(%)"))
        self.label_gain_cut.setText(_translate("MainWindow", "익절 기준(%)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
